# Makefile for eyeDoctor

allall: all 

OTHER_HEADERS=
TARGET=eyeDoctor

# Disable user check to allow running as adamschilperoort
CXXFLAGS += -DXWC_DISABLE_USER_CHECK

include ../../Make/magAOXApp.mk
